# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180119_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
