# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180119_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
