# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180119_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
