# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180201_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewes',
            field=models.IntegerField(default=0),
        ),
    ]
