# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_viewes'),
        ('account', '0002_profile_follows'),
    ]

    operations = [
    ]
