# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180119_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
