# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180119_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date(2018, 1, 19)),
        ),
    ]
