# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='posted_on',
            field=models.DateField(default=datetime.date(2018, 1, 20)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date(2018, 1, 20)),
        ),
    ]
