# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180120_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='posted_on',
            field=models.DateField(default=datetime.date(2018, 1, 25)),
        ),
    ]
