# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180129_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 13, 16, 31, 748255, tzinfo=utc), null=True),
        ),
    ]
