# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180129_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 13, 19, 5, 784333, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Short title of your problem', max_length=70),
        ),
    ]
