# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180129_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='posted_on',
            field=models.DateField(default=datetime.date(2018, 2, 1)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 3, 1, 54, 617532, tzinfo=utc), null=True),
        ),
    ]
