# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180201_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='satisfied',
        ),
        migrations.AddField(
            model_name='answer',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 3, 23, 35, 318969, tzinfo=utc), null=True),
        ),
    ]
