# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180201_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 4, 50, 39, 615150, tzinfo=utc), null=True),
        ),
    ]
