# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180201_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 4, 54, 26, 711213, tzinfo=utc), null=True),
        ),
    ]
