# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180203_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 2, 28, 59, 734906, tzinfo=utc), null=True),
        ),
    ]
