# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180204_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 4, 15, 34, 7, 574463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 15, 34, 7, 558381, tzinfo=utc), null=True),
        ),
    ]
