# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20180204_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='posted_on',
            field=models.DateField(default=datetime.date(2018, 2, 15)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 15, 2, 53, 28, 619519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 2, 53, 28, 619519, tzinfo=utc), null=True),
        ),
    ]
