# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180215_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 15, 3, 27, 58, 236513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 3, 27, 58, 233511, tzinfo=utc), null=True),
        ),
    ]
