# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20180215_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 15, 4, 29, 46, 750449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 4, 29, 46, 750449, tzinfo=utc), null=True),
        ),
    ]
