# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20180215_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 5, 4, 20, 361132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 15, 5, 4, 20, 361132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 5, 4, 20, 345507, tzinfo=utc), null=True),
        ),
    ]
