# Generated by Django 3.1.4 on 2021-01-28 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20180215_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='posted_on',
            field=models.DateField(default=datetime.date(2021, 1, 28)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 17, 45, 56, 483033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 17, 45, 56, 478976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 17, 45, 56, 478976, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
